import Link from "next/link";
import styles from "./page.module.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">


      <body>

        <header style={{ backgroundColor: 'black', padding: '1rem', color: 'white', }}>
          <h2>Header</h2>
          <div className={styles.links}>
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
            <Link href="/about">About</Link>
            <Link href="/blog">Blog</Link>
            <Link href="/contacts">Contacts</Link>
          </div>
        </header>

        {children}

        <footer style={{ backgroundColor: 'grey', padding: '1rem', }}>
          <h2>Footer</h2>
        </footer>

      </body>


    </html>
  )
}
